version: "3.9"  # optional since v1.27.0

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./docker/app/.env
    ports:
      - 4200:4200
    depends_on:
      mysql:
        condition: service_healthy
    mem_limit: 1000m
    mem_reservation: 400m
    cpus: 1
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    env_file:
      - ./docker/mysql/.env
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/mysql --user=$USERNAME --password=$PASSWORD --execute 'SHOW DATABASES';"]
      interval: 4s
      timeout: 2s
      retries: 10
      start_period: 3s
    mem_limit: 1000m
    mem_reservation: 500m
    cpus: 1
