version: 2.1
executors:
  runner:
    machine:
      image: "ubuntu-2004:current"
      docker_layer_caching: true

jobs:
  build:
    docker:
      - image: "circleci/node:10.16.0"
    steps:
      - checkout
      - run:
          name: Install `docker-compose`
          command: |
            curl -L https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Test for ENV
          command: |
            a=123
      - run:
          name: Check docker compose config
          command: |
            docker-compose config
      - run:
          name: Run tests using `docker-compose`
          command: |
            docker-compose up --build --exit-code-from test
