version: 2.1
jobs:
  build:
    docker:
      - image: "circleci/node:10.16.0"
        environment:
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
            MYSQL_DATABASE: $DATABASE
            MYSQL_USER: $DB_USERNAME
            MYSQL_PASSWORD: $DB_PASSWORD
            PORT: $PORT
            DATABASE: $DATABASE
            DB_USERNAME: $DB_USER
            DB_PASSWORD: $DB_PASSWORD
            DB_HOST: $DB_HOST,
            MICROSOFT_CLIENT_ID: $MICROSOFT_CLIENT_ID
            MICROSOFT_CLIENT_SECRET: $MICROSOFT_CLIENT_SECRET
            MICROSOFT_CALL_BACK_URL: $MICROSOFT_CALL_BACK_URL
            MICROSOFT_SCOPE: $MICROSOFT_SCOPE
            SESSION_SECRET: $SESSION_SECRET
            SESSION_RESAVE: $SESSION_RESAVE
            SESSION_SAVEUNINITIALIZED: $SESSION_SAVEUNINITIALIZED,
            SESSION_COOKIE_SECURE: $SESSION_COOKIE_SECURE
            FRONTEND_APP: $FRONTEND_APP
    steps:
      - checkout
      - run:
          name: Install `docker-compose`
          command: |
            curl -L https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker:
          docker_layer_caching: true # should not be important
          version: 20.10.12
      - run:
          name: Build using `docker-compose`
          environment:
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
            MYSQL_DATABASE: $DATABASE
            MYSQL_USER: $DB_USERNAME
            MYSQL_PASSWORD: $DB_PASSWORD
            PORT: $PORT
            DATABASE: $DATABASE
            DB_USERNAME: $DB_USER
            DB_PASSWORD: $DB_PASSWORD
            DB_HOST: $DB_HOST,
            MICROSOFT_CLIENT_ID: $MICROSOFT_CLIENT_ID
            MICROSOFT_CLIENT_SECRET: $MICROSOFT_CLIENT_SECRET
            MICROSOFT_CALL_BACK_URL: $MICROSOFT_CALL_BACK_URL
            MICROSOFT_SCOPE: $MICROSOFT_SCOPE
            SESSION_SECRET: $SESSION_SECRET
            SESSION_RESAVE: $SESSION_RESAVE
            SESSION_SAVEUNINITIALIZED: $SESSION_SAVEUNINITIALIZED,
            SESSION_COOKIE_SECURE: $SESSION_COOKIE_SECURE
            FRONTEND_APP: $FRONTEND_APP
          command: |
            docker-compose up --build --exit-code-from test
