version: 2.1
jobs:
  build:
    docker:
      - image: "circleci/node:10.16.0"
    steps:
      - checkout
      - run:
          name: Install `docker-compose`
          command: |
            curl -L https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker:
          #docker_layer_caching: true # should not be important
          #version: 20.10.12
          name: testing
      - run:
          name: Test for ENV
          command: |
            a=123
      - run:
          name: Check docker compose config
          command: |
            docker-compose config
      - run:
          name: Run tests using `docker-compose`
          command: |
            docker-compose up --build --exit-code-from test
